<a href="https://colab.research.google.com/github/f-ssemwanga/MachineLearning_DeepLearning/blob/main/001_Tensorflowfundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#fundamental concepts of tensors in tensorflow
- introduction to tensors
- getting information from tensors
- changing info in tensors
-tensors and NUMpy
-using @tf.functions  (speeds up regular python functions)
- using GPUs and TensorFlow ( or TPUs)
- Exercises

#Introduction to tensors

In [1]:
#import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.11.0


In [2]:
#Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#check number of dimension (ndim stands for number of dimensions)
scalar.ndim  # returns 0 because the shape attribute is shape()

0

In [4]:
#create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#check dimension of the vector
vector.ndim # look at the tuple in the shape of the vector above - it has one item

1

In [6]:
#create a matric ( has more than one dimension)
matrix = tf.constant([
    [10,7],
    [7,10]
])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [9]:
#create another matrix
another_matrix =tf.constant([
    [10.,7.],
    [3.,2.],
    [8.,9,]],dtype=tf.float16) 
'''
 specify the float data type - the higher the numer in dtype the lower the precision but less
 data is stored, the higher the number e.g. float32 the higher the precision but the larger 
 the data'''
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
#What is the number of dimensions of another_matrix?
another_matrix.ndim

2