<a href="https://colab.research.google.com/github/f-ssemwanga/MachineLearning_DeepLearning/blob/main/002TensorFlow_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Manipulating Tensors (tensor operations)
***Basic Operations***

These are the basic arithmetic operators (+,-,*,/).  These are elementwise operations as they manipulate individual elements in a tensor

In [13]:
import tensorflow as tf

#You can add values to a tensor using the additon Operators
#Note that the original tensor is unchanged.
tensor1 = tf.constant([[10,7],[3,4]])
print(f'Original tensor before operation: {tensor1}')
print(f' Tensor after addition operation: {tensor1 +10}')
print(f'Original tensor before operation: {tensor1}')


Original tensor before operation: [[10  7]
 [ 3  4]]
 Tensor after addition operation: [[20 17]
 [13 14]]
Original tensor before operation: [[10  7]
 [ 3  4]]


In [14]:
#performing an increment operation on the original tensor alters the original tensor
tensor2 = tensor1 +10
print(f'Original tensor before operation: {tensor2}')


Original tensor before operation: [[20 17]
 [13 14]]


In [15]:
#Multiplication operation
print(f'Original tensor before operation: {tensor1}')
print(f' Tensor after addition operation: {tensor1*10}')
print(f'Original tensor before operation: {tensor1}')

Original tensor before operation: [[10  7]
 [ 3  4]]
 Tensor after addition operation: [[100  70]
 [ 30  40]]
Original tensor before operation: [[10  7]
 [ 3  4]]


In [16]:
#Subtraction operation
print(f'Original tensor before operation: {tensor1}')
print(f' Tensor after addition operation: {tensor1-10}')
print(f'Original tensor before operation: {tensor1}')

Original tensor before operation: [[10  7]
 [ 3  4]]
 Tensor after addition operation: [[ 0 -3]
 [-7 -6]]
Original tensor before operation: [[10  7]
 [ 3  4]]


In [18]:
#We can use the tensorflow built in functions too
#the qualified function is tf.math.multiply but we can do the alias which is tf.multiply
#GPU will be faster if you use built in functions
print(f' Tensor after addition operation: {tf.multiply(tensor1,10)}')

 Tensor after addition operation: [[100  70]
 [ 30  40]]


**Matrix Multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.

A good website to visualise this is [Matrix Multiplication.com](http://www.matrixmultiplication.xyz)

In [21]:
#matrix multiplication in tensorflow
print(tensor1)
tf.matmul(tensor1, tensor1)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [25]:
#matrix multiplication with the python "@operator"
tensor1 = tf.constant([[1,2,5],
                    [7,2,1],
                    [3,3,3]])
tensor2 = tf.constant([[3,5],[6,7],[1,8]])

tensor1.shape, tensor2.shape
tf.matmul(tensor1,tensor2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [26]:
#Matrix multiplication in python
tensor1 @ tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [27]:
#Matrix multiplication on tensors of different shapes
#Create a tensor (3,2)
x = tf.constant([[1,2],[3,4],[5,6]])

#create another tensor (3,2)
y = tf.constant([[7,9],[9,10],[11,12]])

x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  9],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [29]:
#Matrix multiplucation of matrix with the same shape
x@y

InvalidArgumentError: ignored

In [30]:
tf.matmul(x,y)

InvalidArgumentError: ignored

**Rules for matrix multiplication**
1. The inner dimensions must match
2. The resulting matrix has the shape of the inner dimensions