<a href="https://colab.research.google.com/github/f-ssemwanga/MachineLearning_DeepLearning/blob/main/004TensorFlow_Fundamentals_Exercises_Challenges.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**Task 1:** 

Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

###**Task 2:**
Find the shape, rank and size of the tensors in 1 above
***

* **Vecor Tensor** also known as a "rank-1" tensor - it is similar to a list of values.  It has **one axis**
* **Scalar Tensor** also known as a "rank-0" tensor - contains a single value.  It has **no axes**
* **Matrix Tensor** also known as a "rank-2" tensor - contains a single value.  It has **two axes**

In [1]:
import tensorflow as tf
import numpy as np
#creating a vector tensor - vector tensor a
vt = tf.constant([2,3,4,5])
st = tf.constant(5)
mt = tf.constant([[2,3,4,5],[5,6,7,8]])
print(f'VECTOR TENSOR: \n{vt}')
print(f'The shape and rank of the VECTOR: Shape:{vt.shape} | Rank:{vt.ndim} | Size:{tf.size(vt)}')
print(f'SCALAR TENSOR: \n{st}')
print(f'The shape and rank of the SCALAR: Shape:{st.shape} | Rank:{st.ndim} |Size:{tf.size(st)} ')
print(f'MATRIX TENSOR: \n{mt}')
print(f'The shape and rank of the MATRIX: Shape:{mt.shape} | Rank:{mt.ndim} Size:{tf.size(mt)} ')


VECTOR TENSOR: 
[2 3 4 5]
The shape and rank of the VECTOR: Shape:(4,) | Rank:1 | Size:4
SCALAR TENSOR: 
5
The shape and rank of the SCALAR: Shape:() | Rank:0 |Size:1 
MATRIX TENSOR: 
[[2 3 4 5]
 [5 6 7 8]]
The shape and rank of the MATRIX: Shape:(2, 4) | Rank:2 Size:8 


###Other forms of creating Tensors
* Creating a random matrix tensor, use the set seed if you need to reproduce the same random values
* Creating a tensor with many dimensions

In [2]:
#Creating multidimensional random tensor
mtDimensionalRandomTensor = tf.constant(tf.random.uniform(shape=[20]), shape=(1,1,1,1,20))
print(f'Multi Dimensional TENSOR: \n{mtDimensionalRandomTensor}')

Multi Dimensional TENSOR: 
[[[[[0.62248003 0.23745298 0.13592172 0.48056245 0.71737194 0.13415587
     0.35207748 0.9892303  0.8589034  0.08430719 0.5647119  0.05681407
     0.75971806 0.14468849 0.48205912 0.30645227 0.9065207  0.92217755
     0.4819578  0.94967496]]]]]


In [3]:
myRandomTensor = tf.random.Generator.from_seed(42)
myRandomTensor = myRandomTensor.normal(shape=(3,4))
print(f'RANDOMLY GENERATED MATRIX WITH SEED: \n{myRandomTensor}')
print(f'The shape of the Tensor above is: {myRandomTensor.shape}')
print(f'The above tensor has {myRandomTensor.ndim} dimensions')

RANDOMLY GENERATED MATRIX WITH SEED: 
[[-0.7565803  -0.06854702  0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855   0.09988727 -0.50998646]
 [-0.7535805  -0.57166284  0.1480774  -0.23362993]]
The shape of the Tensor above is: (3, 4)
The above tensor has 2 dimensions


In [4]:
#Creating a tensor with many dimensions
fourDimensionalTensor =tf.ones(shape=(3,2,5,4))
print(f'FOUR DIMENSIONAL TENSOR: \n{fourDimensionalTensor}')
print(f'The shape of the Tensor above is: {fourDimensionalTensor.shape}')
print(f'The above tensor has {fourDimensionalTensor.ndim} dimensions')

FOUR DIMENSIONAL TENSOR: 
[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]
The shape of the Tensor above is: (3, 2, 5, 4)
The above tensor has 4 dimensions


###**Task 3:**
Create two tensors containing random values between 0 and 1 with the shape [5,300]

In [5]:
randomTensor1 = tf.random.uniform(shape=[5,300], minval=0, maxval =1)
randomTensor2 = tf.random.uniform(shape=[5,300], minval=0, maxval =1)
randomTensor1, randomTensor2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.9513515 , 0.05954897, 0.5427717 , ..., 0.20032203, 0.4192798 ,
         0.01746035],
        [0.6388607 , 0.11860454, 0.85116386, ..., 0.8048589 , 0.7949796 ,
         0.45094383],
        [0.77619565, 0.5013428 , 0.43337572, ..., 0.38632905, 0.3054489 ,
         0.3932233 ],
        [0.7338699 , 0.52914286, 0.5533248 , ..., 0.66253364, 0.8472798 ,
         0.60013115],
        [0.97258365, 0.585955  , 0.5048735 , ..., 0.8296194 , 0.02046001,
         0.235371  ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.1197257 , 0.10300386, 0.39281356, ..., 0.08945763, 0.60827553,
         0.13469946],
        [0.0290947 , 0.9622742 , 0.5436845 , ..., 0.19762743, 0.98567545,
         0.31664777],
        [0.3446325 , 0.42943907, 0.1516465 , ..., 0.60300374, 0.41014874,
         0.51673996],
        [0.30744135, 0.49007475, 0.3270887 , ..., 0.42348492, 0.77181053,
         0.3278836 ],
        [0.48945

###**Task 4:**
Multiply the two tensors created in task 3 using matrix multiplication

In [6]:
#check the shapes of the two tensors
randomTensor1.shape, randomTensor2.shape

(TensorShape([5, 300]), TensorShape([5, 300]))

**We will need to reshape or transpose one of them to meet the rules of matrix multiplication**

In [7]:
#reshape randomTensor1 and them perform matrix multiplication
reShaped = tf.reshape(randomTensor1, shape=(300,5))
myProduct = tf.matmul(reShaped,randomTensor2) 
print(f'The product of randomTensor1 of shape{reShaped.shape} * randomTensor2 of shape{randomTensor2.shape} is: \n{myProduct}')


The product of randomTensor1 of shape(300, 5) * randomTensor2 of shape(5, 300) is: 
[[0.7298109  0.6621652  0.8239149  ... 0.9813109  1.3166461  0.7388475 ]
 [0.7925889  0.7673876  0.7158592  ... 1.1597219  1.091702   0.8392724 ]
 [0.6848147  1.1931742  0.96539146 ... 1.0225464  1.8387027  0.9017903 ]
 ...
 [0.79754066 0.9484687  0.8745519  ... 1.1504228  1.4534844  0.87532294]
 [0.5231439  0.8013629  0.6429248  ... 0.77946943 1.1245224  0.6145375 ]
 [0.452525   1.0889038  0.6687902  ... 0.810996   1.233569   0.7532498 ]]


###**Task 5:**
Multiply the two tensors created in task 3 using dot product

In [8]:
tf.tensordot(randomTensor1,randomTensor2, axes=0)

<tf.Tensor: shape=(5, 300, 5, 300), dtype=float32, numpy=
array([[[[1.13901228e-01, 9.79928821e-02, 3.73703778e-01, ...,
          8.51056501e-02, 5.78683853e-01, 1.28146544e-01],
         [2.76792832e-02, 9.15461004e-01, 5.17235041e-01, ...,
          1.88013151e-01, 9.37723815e-01, 3.01243335e-01],
         [3.27866673e-01, 4.08547521e-01, 1.44269124e-01, ...,
          5.73668540e-01, 3.90195638e-01, 4.91601348e-01],
         [2.92484790e-01, 4.66233373e-01, 3.11176360e-01, ...,
          4.02883023e-01, 7.34263122e-01, 3.11932564e-01],
         [4.65646476e-01, 1.66805267e-01, 3.27333182e-01, ...,
          5.97307563e-01, 2.98710108e-01, 2.92832047e-01]],

        [[7.12954300e-03, 6.13377430e-03, 2.33916454e-02, ...,
          5.32711018e-03, 3.62221822e-02, 8.02121498e-03],
         [1.73255929e-03, 5.73024414e-02, 3.23758535e-02, ...,
          1.17685106e-02, 5.86959608e-02, 1.88560504e-02],
         [2.05225125e-02, 2.55726557e-02, 9.03039332e-03, ...,
          3.59082557e-0

###**Task 6 :**
Create a tensor with  random values between 0 and 1 with shape [224, 224, 3].

In [9]:
randomTensor3 = tf.random.uniform(shape=[224,224,3], minval=0, maxval =1)
randomTensor3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7096741 , 0.71764004, 0.75189865],
        [0.00161803, 0.983358  , 0.03720808],
        [0.65829444, 0.73354876, 0.7413589 ],
        ...,
        [0.5796703 , 0.3784685 , 0.17923927],
        [0.6375853 , 0.786018  , 0.58259034],
        [0.9034704 , 0.65686905, 0.11999285]],

       [[0.23985791, 0.60213256, 0.19161761],
        [0.7191279 , 0.89865386, 0.34637678],
        [0.32481122, 0.6515721 , 0.021644  ],
        ...,
        [0.6787046 , 0.9760648 , 0.19182122],
        [0.03729057, 0.25753784, 0.3052919 ],
        [0.9307481 , 0.7598289 , 0.50183797]],

       [[0.53529906, 0.90305185, 0.81784356],
        [0.6045042 , 0.86042726, 0.8070841 ],
        [0.9034643 , 0.32577813, 0.3321712 ],
        ...,
        [0.2105633 , 0.03988898, 0.67270315],
        [0.3824787 , 0.9085922 , 0.7379098 ],
        [0.6137519 , 0.9075686 , 0.94727266]],

       ...,

       [[0.7897465 , 0.5054765 , 0.45282447],
        [0.91

###**Task 7 :**
Find the min and max values of the tensor created in task 6 along the first axis.

In [10]:
tf.argmax(randomTensor3), tf.argmin(randomTensor3)


(<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
 array([[ 35, 121,   8],
        [118, 160,  33],
        [169, 169,  73],
        [ 29, 105, 106],
        [173, 213, 200],
        [ 12,  85, 202],
        [  0,   4, 200],
        [ 69,  58, 118],
        [202,  62,  39],
        [ 39, 113,   4],
        [222,  88, 158],
        [ 24, 120, 220],
        [ 97, 113,  34],
        [ 72, 210,  54],
        [205,  49, 106],
        [222,  21,  38],
        [ 32,  35,   2],
        [178, 179,  42],
        [132,  16,  92],
        [209, 189,  45],
        [159, 101, 211],
        [ 76, 162, 124],
        [159,  22,  80],
        [219, 200, 223],
        [129, 104, 145],
        [ 84, 168, 221],
        [ 59, 198, 203],
        [115, 196, 167],
        [129, 184,  15],
        [215, 104,  92],
        [ 65,  28, 109],
        [ 48, 198,  73],
        [  3, 133,  76],
        [ 83, 126, 178],
        [144,   2,  39],
        [188, 118, 197],
        [ 76, 134, 182],
        [129, 177, 192],
 

##**Task8:** Create a tensor with random values of shape [1,224,224,3] then squeese it to change the shape to [224,224,3]

In [11]:
toSqueeze = tf.random.uniform(shape=[1,224,224,3])
toSqueeze

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.63436234, 0.16818881, 0.9107095 ],
         [0.7138903 , 0.8961617 , 0.91772723],
         [0.358294  , 0.03805566, 0.26295936],
         ...,
         [0.8894799 , 0.76154256, 0.4515133 ],
         [0.20234919, 0.60157895, 0.84922326],
         [0.51395094, 0.9944223 , 0.9698163 ]],

        [[0.26146328, 0.55105865, 0.8116112 ],
         [0.1139214 , 0.6349273 , 0.98299944],
         [0.5484841 , 0.8054513 , 0.01897466],
         ...,
         [0.8921764 , 0.39183617, 0.02986908],
         [0.32899857, 0.9054967 , 0.7488525 ],
         [0.48028755, 0.11111224, 0.8659482 ]],

        [[0.43741035, 0.7972456 , 0.7261113 ],
         [0.39847338, 0.5133184 , 0.633381  ],
         [0.5684247 , 0.5219933 , 0.65820384],
         ...,
         [0.5395702 , 0.8332375 , 0.35494578],
         [0.2734437 , 0.05154514, 0.7487756 ],
         [0.27540922, 0.7724192 , 0.9067563 ]],

        ...,

        [[0.07961309, 0.5477514 , 

In [12]:
#squeeze the tensor above
squeezedTensor = tf.squeeze(toSqueeze)
squeezedTensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.63436234, 0.16818881, 0.9107095 ],
        [0.7138903 , 0.8961617 , 0.91772723],
        [0.358294  , 0.03805566, 0.26295936],
        ...,
        [0.8894799 , 0.76154256, 0.4515133 ],
        [0.20234919, 0.60157895, 0.84922326],
        [0.51395094, 0.9944223 , 0.9698163 ]],

       [[0.26146328, 0.55105865, 0.8116112 ],
        [0.1139214 , 0.6349273 , 0.98299944],
        [0.5484841 , 0.8054513 , 0.01897466],
        ...,
        [0.8921764 , 0.39183617, 0.02986908],
        [0.32899857, 0.9054967 , 0.7488525 ],
        [0.48028755, 0.11111224, 0.8659482 ]],

       [[0.43741035, 0.7972456 , 0.7261113 ],
        [0.39847338, 0.5133184 , 0.633381  ],
        [0.5684247 , 0.5219933 , 0.65820384],
        ...,
        [0.5395702 , 0.8332375 , 0.35494578],
        [0.2734437 , 0.05154514, 0.7487756 ],
        [0.27540922, 0.7724192 , 0.9067563 ]],

       ...,

       [[0.07961309, 0.5477514 , 0.6464083 ],
        [0.60

##**Task9:** Create a tensor with shape [10] using your own choice of values, then find the index which has then maximum value.

In [14]:
myChoiceTensor =tf.random.uniform(shape=[10])
myChoiceTensor

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.57211876, 0.2512318 , 0.758132  , 0.4045962 , 0.21238863,
       0.766436  , 0.16788268, 0.5763881 , 0.962096  , 0.11677349],
      dtype=float32)>

In [15]:
print(f'The maximum value of the above tensor is at index: {tf.math.argmax(myChoiceTensor)}')

The maximum value of the above tensor is at index: 8


##**Task 10:** One-hot encode the tensor created in 9 above

In [23]:
myChoiceTensor.dtype
#cast the above tensor into a int32
toEncode = tf.cast(myChoiceTensor,dtype = tf.int32)
#toEncode.dtype, myChoiceTensor.dtype
tf.one_hot(toEncode,depth=4, on_value="1.", off_value="0.")

<tf.Tensor: shape=(10, 4), dtype=string, numpy=
array([[b'1.', b'0.', b'0.', b'0.'],
       [b'1.', b'0.', b'0.', b'0.'],
       [b'1.', b'0.', b'0.', b'0.'],
       [b'1.', b'0.', b'0.', b'0.'],
       [b'1.', b'0.', b'0.', b'0.'],
       [b'1.', b'0.', b'0.', b'0.'],
       [b'1.', b'0.', b'0.', b'0.'],
       [b'1.', b'0.', b'0.', b'0.'],
       [b'1.', b'0.', b'0.', b'0.'],
       [b'1.', b'0.', b'0.', b'0.']], dtype=object)>