<a href="https://colab.research.google.com/github/f-ssemwanga/MachineLearning_DeepLearning/blob/main/TensorFlow_fundamentals003.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Tensors and Numpy**

Numpy is the fundamental package for scientific computing with python

* Numpy is built upon the numpy array object
* Tensorflow interacts beautifully with Numpy arrays
* Benefit of converting tensors to numpy array is that if there is a functionality that is not working within a tensor e.g. access to an element you can convert the tensor to a numpy array and access data as showin in cell 5
* The default type for a tensor from a numpy array is float64 where as the default type of a tensor is float32.  We saw this when working out standard deviation and variance, See check in cell 9

In [3]:
import tensorflow as tf
import numpy as np

#create a tensor directly from a Numpy array
J = tf.constant(np.array([3.,7., 10.,]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [4]:
#Convert tensor J into a Numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [5]:
#Alternative way of converting a tensor to a numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [7]:
J.numpy()[2] #gives access to the element at position 2


10.0

In [10]:
#The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,5., 9.]))
tensor_J = tf.constant([3.,5., 9.])

#check the data types of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)