<a href="https://colab.research.google.com/github/f-ssemwanga/MachineLearning_DeepLearning/blob/main/TensorFlow_fundamentals003.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Tensors and Numpy**

Numpy is the fundamental package for scientific computing with python

* Numpy is built upon the numpy array object
* Tensorflow interacts beautifully with Numpy arrays
* Benefit of converting tensors to numpy array is that if there is a functionality that is not working within a tensor e.g. access to an element you can convert the tensor to a numpy array and access data as showin in cell 5
* The default type for a tensor from a numpy array is float64 where as the default type of a tensor is float32.  We saw this when working out standard deviation and variance, See check in cell 9
* Tensorflow tensor can be run on a GPU or TPU for faster numeric processing

In [3]:
import tensorflow as tf
import numpy as np

#create a tensor directly from a Numpy array
J = tf.constant(np.array([3.,7., 10.,]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [4]:
#Convert tensor J into a Numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [5]:
#Alternative way of converting a tensor to a numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [6]:
J.numpy()[2] #gives access to the element at position 2


10.0

In [7]:
#The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,5., 9.]))
tensor_J = tf.constant([3.,5., 9.])

#check the data types of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

##Finding Access to GPUs

* Using **tf.config.list_physical_devices** - to return a list of physical devices visible to the host runtime
*To access a free GPU/TPU - go to the **Runtime menu**and choose **Change Runtime type**

In [10]:
#using tf.config to find list of accessible devices
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [11]:
tf.config.list_physical_devices("GPU") # currently shows no access to GPU

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [13]:
#checking the type of GPU
!nvidia-smi

Mon Mar 20 13:49:39 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P0    28W /  70W |    341MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Note: ** If you have access to CUDA enabled GPU, Tensorflow will automatically use it whenever possible